[theme]

primaryColor = "#0077b6"          
backgroundColor = "#f0f4f8"       
secondaryBackgroundColor = "#ffffff"  
textColor = "#03045e"             
font = "sans serif"

# For charts, we will use colorblind-friendly palette
[theme.plotly]
colorway = ["#0077b6", "#0096c7", "#00b4d8", "#48cae4", "#90e0ef", "#ade8f4"]
